---
- hosts: 172.31.13.127
  become: yes
  tasks:
    - name: i want to run linux command on node
      command: hostname -f
      register: myresult

    - name: i want to display linux command ouput
      debug:
         msg: "{{myresult}}"

- name: i want to install git
      apt: 
         name: git
         state: present
      when: myresult.stderr!= ""


- name: i want to install apache2
      apt:
         name: apache2
         state: present
      when: myresult.stderr== ""
