---
- hosts: 172.31.13.127
  become: yes
  tasks:
      - include_tasks: myfile.yml

      - name: i want to install apache2
        apt:
            name: apache2
            state: present
        notify: restartwebserver

      - name: i want to replace apache2 template with my jinja template
        template:
            src: index.j2
            dest: /var/www/html/index.html
        notify: restartwebserver


  handlers:
     - name: restartwebserver
       service:
          name: apache2
          state: restarted 

   