---
- hosts: all
  become: yes
  tasks:
         - name: i want to install java openjdk-8-jre-headless  on ubuntn server
           apt:
                   name: openjdk-8-jre-headless
                   state: present