---
- hosts: 172.31.13.127
  become: yes
  vars:
   myvar1 : tree
   myvar2 : git
   myvar3 : apache2
  tasks:
      - name: i want to display variable value
        debug:
            msg : "{{myvar2}}"

      - name:  i want to install git,tree and apache2
        apt:
           name: "{{item}}"
           state: present
        loop: 
        - "{{myvar1}}"
        - "{{myvar2}}"
        - "{{myvar3}}"