---
- hosts: all
  become: yes
  tasks:
         - name: i want to install apache2 in node1
           apt:
                   name: apache2
                   state: present
           when: ansible_os_family == "Debian"    

         - name: i want to instal apache2 in redhat ansible node
           yum:
                   name: httpd
                   state: present 
           when: ansible_os_family == "RedHat"

         - name: start service httpd, if not stared
           service:
                   name: httpd
                   state: restarted
                   enabled: yes