---
# tasks file for mywebrole
         - name: i want to install apache2 in node133333
           apt:
                   name: "apache2"
                   state: present
           when: ansible_os_family == "Debian"    

         - name: Change Apache2 template with Jinja template
           template:
              src: index.j2
              dest: /var/www/html/index.html   
